### ISSUE TITLE
Does not work on Ubuntu 20.04 with the default installation steps.

### ISSUE THREAD

**Issue by ilap** [Blockchain-Technology-Lab/Rewards-Sharing-Simulation-Engine#5]
By default Ubuntu 20.04 only has python3.8.

Luckily, python3.9 is added to the `focal-updates/main` repository which can be installed/configured with some dependencies, see details below, to get the engine be able to run on 20.04

###  Install the engine and the python3.9
``` bash
$ git clone https://github.com/Blockchain-Technology-Lab/Rewards-Sharing-Simulation-Engine
$ cd Rewards-Sharing-Simulation-Engine
$ sudo apt update
$ sudo apt install python3.9
```

### Install pip3.9 for python3.9
``` bash
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3.9 get-pip.py --user
$ pip3 --version
pip 22.2.2 from /home/ilap/.local/lib/python3.9/site-packages/pip (python 3.9)
# If it shows: 
# pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
# then use pip3.9 instead.
```

### Install simulations engines' pre-requisities
``` bash
$ pip3.9 install -U Pillow --user
$ python3.9 -m pip install -r requirements.txt
```

### Run simulation engine
Pls note that `--a0` is the correct parameter instead of  `--alpha`, mentioned in [README.md](https://github.com/Blockchain-Technology-Lab/Rewards-Sharing-Simulation-Engine#using-the-simulation-engine) 
``` bash
$ python3.9 batch-run.py --n=3198 --k=500  --a0=0.3 --execution_id=mainnet_simulation
```

**Comment by LadyChristina** [comment]
Hi @ilap, thanks for taking the time to write this. I corrected the command in [README.md](README.md) and I can update the installation instructions when I have more time (but also feel free to make the changes yourself and open a pull request if you want)

**Comment by ilap** [comment]
Hi @LadyChristina, I will do thx.
